name: Rspec
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  rspec_gec1:
    name: SPEC
    runs-on: ubuntu-latest     
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch_name }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0


      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependent libraries
        run: |
          sudo apt-get install sqlite3


      - name: Install gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:test:prepare
        env:
          RAILS_ENV: test

      - name: Run RSpec
        run: bundle exec rspec .
        env:
          RAILS_ENV: test

